remote_theme: wet-boew/gcweb-jekyll
title: Mon site d'essaie

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

# Global
global:
  gcds: true
